### ISSUE TITLE
 Where is the segmented_content.txt file used to build Vocab?

### ISSUE THREAD

**Issue by ChenLeeStu** [lancopku/Graph-to-seq-comment-generation#6]
https://github.com/lancopku/Graph-to-seq-comment-generation/blob/8f66c2c956ff394aeb210a0777bb8c2e7ee0a8cb/train.py#L217

**Comment by liweitj47** [comment]
it can be extracted from the json file

**Comment by DesmonDay** [comment]
Hi. Do you know where is the module `graph_tool`?

**Comment by DesmonDay** [comment]
@liweitj47 Hello. Does the `segged_content.txt` should contain the content of dev file and test file?

**Comment by shenjian5** [comment]
> it can be extracted from the json file

能告知一下"segged_content.txt"最终抽取后的格式是？
